import Script from "next/script";
import type { Metadata } from "next";

import "./globals.css";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html lang="en">
        <head>
          <Script
            id="adsense-script"
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
            data-ad-client="ca-pub-1772060773365341"
            strategy="afterInteractive"
          />
        </head>
        <body className={`${inter.variable} antialiased`}>
          {children}
        </body>
      </html>
    );
}
